config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :skip => [:sessions, :registrations, :passwords]
  devise_scope :user do
  	post '/login' => 'sessions#create', :as => :user_session
    delete '/logout' => 'sessions#destroy', :as => :destroy_user_session
  end
  resources :videos, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :videos, class_name: "Video"
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  validates :url, format: { with: /(youtu\.be\/|youtube\.com\/(watch\?(.*&)?v=|(embed|v)\/))([^\?&"'>]+)/ }, presence: true

  after_create :update_embad_url

  private

  def update_embad_url
  	update(url: YoutubeGenerator.video_embed(self.url))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @videos = Video.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    resource = User.find_by(email: user_params[:email])
    resource = User.create!(user_params) unless resource
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to root_path, notice: "Succeessfully Signin"
  end

  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!

  def new
    @video = Video.new
  end

  def create
    @video = current_user.videos.build(video_params)
    if @video.save
      redirect_to root_path, notice: "Successfully shared movie."
    else
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.erb
<div class="container">
  <% @videos.each do |video| %>
    <div class="well p-2">
      <div class="media">
        <div class="video-fluid embed-responsive embed-responsive-16by9">
          <iframe width="50px" height="50px" class="embed-responsive-item" src="<%= video.url %>" allowfullscreen></iframe>
        </div>
        <div class="media-body ml-5">
          <h4 class="media-heading">Movie Title</h4>
            <p>Shared By <%= video.user.email %></p>
            <p>Description</p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate. 
              Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero.
            </p>
            <ul class="list-inline list-unstyled">
              <li class="float-left mr-1"><span><i class="glyphicon glyphicon-calendar"></i> <%= video.created_at.strftime("%FT%T")%> </span></li>
            </ul>
         </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
  <div class="container">
    <a class="navbar-brand" href="/">Funny Movies</a>
    <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <div class="collapse navbar-collapse" id="exCollapsingNavbar">
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto action-buttons">
          <li class="nav-link mr-4">Welcome <%= current_user.email %></li>
          <li>
            <%= link_to 'Share a movie', new_video_path, class: 'btn btn-primary mr-4' %>
          </li>
          <li>
            <%= link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'btn btn-primary' %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
          <li class="dropdown order-1">
            <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle">Login / Register<span class="caret"></span></button>
            <ul class="dropdown-menu dropdown-menu-right mt-2">
             <li class="px-3 py-2">
               <%= form_for(resource, as: resource_name, url: user_session_path(resource_name)) do |f| %>
                  <div class="form-group">
                    <%= f.email_field :email, autofocus: true, autocomplete: 'email', placeholder: "Email", class: 'form-control form-control-sm', required: true %>
                  </div>
                  <div class="form-group">
                    <%= f.password_field :password, autocomplete: 'current-password', class: 'form-control form-control-sm', placeholder: "Password", required: true %>
                  </div>
                  <div class="form-group">
                    <%= f.submit "Login / Register", class: 'btn btn-primary' %>
                  </div>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container">
      <main role="main">
         <%= render 'layouts/messages' %>
         <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/videos/new.html.erb
<div class="d-flex justify-content-center align-items-center container-fluid h-100 bg-light text-dark">
  <div class="col col-sm-6 col-md-6 col-lg-4 col-xl-10">
    <%= form_for(@video) do |f| %>
      <% if @video.errors.any? %>
        <% @video.errors.full_messages.each do |message|%>
        <h3><%= message %> </h3>
        <%end%>
      <%end%>
      <div class="form-group row">
        <label for="inputUrl" class="col-sm-2 col-form-label mr-5">Youtube URL</label>
        <div class="col-sm-10">
          <%= f.text_field :url, class: "form-control", placeholder: "Youtube URL", reuired: true %>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    <% end %>
  </div>
</div>